version: "3.5"
services:

  cve_search:
    image: cve_search
    build:
      context: .
      dockerfile: dockerfile-cve_search
    hostname: cve_search
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
      - cronjob
    restart: always
    environment:
      - PYTHONUNBUFFERED=TRUE
      - WORKER_SIZE=2
    networks:
      - default

  cronjob:
    image: cron_job
    build:
      context: .
      dockerfile: dockerfile-cve_cron_job
    networks:
      - default

  redis:
    image: cve_search-redis
    hostname: redis
    build:
      context: .
      dockerfile: dockerfile-redis
    restart: always    
    volumes:
      - "redis-data:/usr/local/etc/redis"
    networks:
      - default

  mongo:
    image: cve_search-mongo
    hostname: mongo
    build:
      context: .
      dockerfile: dockerfile-mongo
    restart: always    
    volumes:
      - "mongo:/data/db"
    networks:
      - default

volumes:
  mongo:
  redis-data: